workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        environment:
          android_signing:    
            - codemagicKey
          vars:
            PACKAGE_NAME: "com.anonymous.RNCodePushDemo"
        scripts:
          - name: Set Android SDK location
            script: | 
              echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          - name: Install npm dependencies
            script: | 
              npm install
          - name: Run Expo Prebuild
            script: | 
              npx expo prebuild --platform android
          - name: Set up app/build.gradle
            script: |
              mv ./support-files/build.gradle android/app   
          - name: Build Android release
            script: | 
              cd android
              # ./gradlew bundleRelease
              ./gradlew assembleRelease
        artifacts:
          - android/app/build/outputs/**/*.aab
          - android/app/build/outputs/**/*.apk